FROM python:3.10-slim

WORKDIR /app

# 添加腾讯云 pip 源
RUN pip config set global.index-url https://mirrors.cloud.tencent.com/pypi/simple

# 安装 ffmpeg
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt 

COPY . .

# Expose the port that the application runs on
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]